DROP TABLE IF EXISTS LOGIN;
CREATE TABLE LOGIN(ID INT AUTO_INCREMENT PRIMARY KEY,
   email_id VARCHAR(255),
    password VARCHAR(255),
     secrete_code VARCHAR(255));
INSERT INTO LOGIN VALUES( '1','faizal@123', '123','5678');
INSERT INTO LOGIN VALUES( '2','mohd@234' , '546', '1267');



DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(ID INT AUTO_INCREMENT PRIMARY KEY,
   email_id VARCHAR(255),
    comment VARCHAR(255),
     );
INSERT INTO COMMENT VALUES('1', 'faizal@123', 'comment first for check');
INSERT INTO COMMENT VALUES('2', 'mohd@234' , 'comment by mohamed');